### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by juliavankirk** [DIT112-V21/group-07#11]
As a User, I want to have an app I can utilize to control the car with so I may manually drive.

Acceptance Criteria:
Car moves accurately as commanded via the app.

**Comment by juliavankirk** [comment]
Drafted a prototype of the app:
https://www.figma.com/file/PJevrYL9gbFVFapYn8qYeV/pathfinder?node-id=0%3A1

**Comment by alrapal** [comment]
I close this issue since the merge #31 solved it
