### ISSUE TITLE
Merge to Master

### ISSUE THREAD

**Issue by bassamEldesouki** [DIT112-V21/group-07#19]
All the code from all branches that has needed code for the demo shall be merged to master branch.

**Comment by bassamEldesouki** [comment]
Successfully merging to master is finished.

**Comment by juliavankirk** [comment]
Could we actually approve my PR to remove .idea/ from our repo? Please and thank you :)

**Comment by bassamEldesouki** [comment]
Yes :) I will look at it now!

**Comment by bassamEldesouki** [comment]
@juliavankirk  Your PR is also now merged to master, have a look at close this issue please if everything is okay :)

**Comment by juliavankirk** [comment]
@bassamEldesouki all good, thanks so much!!
