### ISSUE TITLE
Accident prevention behavior  

### ISSUE THREAD

**Issue by ChrisAxt** [DIT112-V21/group-07#2]
**User Story:** 
As a driver I want the vehicle to prevent me from driving in a dangerous way so that I do not cause an accident. 

**Acceptance Criteria:** 
2.1 As soon as the car detects an obstacle at a distance of 70cm (safety range), the car should stop moving as fast as possible. 
2.2 The car shall not allow the driver / user to move towards a direction where an obstacle has been detected. The safety area should be 40cm.
2.3 The car driver shall have control of the car after it has stopped and attempted avoiding an accident.
2.4 The system should notify the driver in case of emergency and display the reason.
2.5 If an obstacle is detected, getting closer on either side of the car, the car should try to move in the other direction (45° steering angle) until the sensor does not detect anything within the range 0-35cm.

**Comment by alrapal** [comment]
This [commit](https://github.com/DIT112-V21/group-07/commit/f0faf577712db66ed46dce8731a89a0b37472c96) was a try for changing the tags but it did not work as expected. 
Not needed to be taken in consideration.

**Comment by bassamEldesouki** [comment]
Done and merged to master!
