### ISSUE TITLE
[CI] Setting-up Arduino_CI_build framework

### ISSUE THREAD

**Issue by ediz-genc** [DIT112-V21/group-07#20]
**Description**
The Arduino_CI build is needed to be modified for the smart car by adding MQTT, WIFI as well as camera options so that all the new code snippets we are introducing to the system are implemented faultless.

**To-Do**
20.1 Arduino_CI build should be executed for each new push.
20.2 Arduino_CI should regardless return the result of the build each time when the new codes pushed.

**Comment by alrapal** [comment]
I close this issue, resolved with issue #38

**Comment by bassamEldesouki** [comment]
@alrapal This issue shouldn't be closed now, The CI still needs to be improved :) So it will follow to sprint 2

**Comment by alrapal** [comment]
Ok, my bad !
🤫

**Comment by ediz-genc** [comment]
This task enhanced by adding mqtt, wifi, and camera to the installations in Arduino_build.yml by @edizgenc2021 and @bassamEldesouki with PR #26 #27, therefore it is going to be closed as it is done.
