### ISSUE TITLE
Scope definition

### ISSUE THREAD

**Issue by iachella** [DIT112-V21/group-07#23]
## Description:
Create documentation related to the scope of the project.
- [Project charter](https://docs.google.com/document/d/17YulOEnE0E8m2PlIp4_RylS-U6Qdn08oXvR8owIAqz4/edit?usp=sharing) with scope statement

### Project charter:
- What will be part of the project
- What will not be part of the project
- To be defined (things that we don't have enough knowledge/experience about, yet).
- Constrains
- Assumptions
- Goal
- Objectives
- Deliverables
- Stakeholders
- Team members
- Exit criteria
- Summary of milestones
- Start and exit date of projects

**Comment by alrapal** [comment]
Project charter : in this [file](https://docs.google.com/document/d/17YulOEnE0E8m2PlIp4_RylS-U6Qdn08oXvR8owIAqz4/edit?usp=sharing)

**Comment by alrapal** [comment]
Review required by: 
@juliavankirk 
@edizgenc2021 
@bassamEldesouki 
@gusaxtcha

**Comment by platisd** [comment]
@alrapal why don't you assign them to the PR?

**Comment by alrapal** [comment]
@platisd  
We agreed working on a google document file first. Therefore there is not PR possible yet. 
Would you recommend creating a document on GitHub directly?

**Comment by platisd** [comment]
I thought this was a pull request, nevermind.

**Comment by iachella** [comment]
Scope definition related to Sprint 1 and 2 has been discussed (more info in our [meeting document](https://docs.google.com/document/d/19yXmb05ovpGvVFWtIMncVmlf0xZ0gMhrnyFqY1uUTNc/edit?usp=sharing)). We will continue adapting the scope of our project if necessary, and new issues can be created for that.
