### ISSUE TITLE
[BUG] Multiple button interaction before car follows instructions

### ISSUE THREAD

**Issue by alrapal** [DIT112-V21/group-07#47]
## Current behaviour
Sometimes we need to press multiple times a button for the car to actually obey the instruction
***
## Expected behaviour
Pressing one time should be enough to get the car doing what is expected (if possible). 
***

**Comment by alrapal** [comment]
It might be solved with #48, caused by #49  could have been because the car detecting obstacles preventing the car to move (until the direction was set to the opposite side) 
Needs further test to be sure it is solved.

**Comment by ChrisAxt** [comment]
Could not reproduce this bug, it seems to have been corrected in a previous bug fix (#48 ).

**Comment by juliavankirk** [comment]
Could this have been a QoS issue, with messages being dropped?

**Comment by alrapal** [comment]
> Could this have been a QoS issue, with messages being dropped?

If I remember correctly, the problem was coming from the odometers. 
When receiving an input, the car checked the sensors based on the direction given by the odometers. (1 for forward, -1 for backward).
But when it stops the odometer send the last direction they used, which was messing up with the sensor checking. 
So if you moved forward and stop because of an obstacle. When trying to go backwards it could still check the front sensor and stop the car directly since the obstacle was still there. 
So we added a check for the speed also for another bug and it solved this one basically.
