### ISSUE TITLE
Slow down smoothly

### ISSUE THREAD

**Issue by alrapal** [DIT112-V21/group-07#5]
#### User story:
As a user, I want the vehicle to slow down smoothly if it detects an obstacle at the front so that I can react on time and avoid it.
***
#### Acceptance Criteria: 
- Vehicle slows down smoothly  when detecting an obstacle between 250 cm and 70
- The user can still control the vehicle under this time. 
- If no reaction from the user, the vehicle will stop when the obstacle is entering the safety zone (0 to 70cm). -> #2 should take over

**Comment by ChrisAxt** [comment]
The issue has been completed in terms of the acceptance criteria, can be enhanced at a later stage if needed.
