### ISSUE TITLE
[BUG] Impossible to move backwards when moving forward

### ISSUE THREAD

**Issue by alrapal** [DIT112-V21/group-07#55]
## Current behaviour
When telling the car to move forward, you cannot directly ask for moving backward, you have to stop first.
This only happens when using the upper arrow from the app. Not the side arrows
***
## Expected behaviour
It should be possible to go backward without breaking before.
***
## Possible fix
Wait for #42 before trying to fix. Might disappear when changing the arrows for another type of control

**Comment by ChrisAxt** [comment]
I believe this bug is solved with the implementation of the joystick

**Comment by ChrisAxt** [comment]
Closing for the reason stated above.
