### ISSUE TITLE
Finding the original trajectory!

### ISSUE THREAD

**Issue by ChrisAxt** [DIT112-V21/group-07#6]
**User Story:**
As the user, I want the vehicle to continue driving on its original course after it has avoided obstacles so that it can continue on its course in a satisfactory way.

**Acceptance Criteria:** 
The vehicle is able to continue on its original trajectory after avoiding the obstacle.

**Comment by bassamEldesouki** [comment]
This user story is not doable as the emulator can't provide us the car's position.

**Comment by bassamEldesouki** [comment]
After asking the TAs, this could be done by using the camera feature! "Image processing". Could be implemented in later sprints.

**Comment by platisd** [comment]
> After asking the TAs, this could be done by using the camera feature! "Image processing". Could be implemented in later sprints.

I don't know who you talked to and what they or you have in mind, but that sounds particularly challenging...

**Comment by bassamEldesouki** [comment]
> > After asking the TAs, this could be done by using the camera feature! "Image processing". Could be implemented in later sprints.
> 
> I don't know who you talked to and what they or you have in mind, but that sounds particularly challenging...

This issue is restored after the info we have got from the TAs, we had actually nothing in mind and we all decided to close it but we have been told that it's doable and NOT Challenging so maybe we can implement it later if we have time for it. That's why it's restored but not assigned to any sprint.  " If the TAs provides wrong info then this is a problem " !

**Comment by AeroStun** [comment]
I fail to see how you would need an exact 3D position to begin with; if all you care is a trajectory (i.e. a direction), the gyroscope is your friend.

**Comment by platisd** [comment]
> > > After asking the TAs, this could be done by using the camera feature! "Image processing". Could be implemented in later sprints.
> > 
> > 
> > I don't know who you talked to and what they or you have in mind, but that sounds particularly challenging...
> 
> This issue is restored after the info we have got from the TAs, we had actually nothing in mind and we all decided to close it but we have been told that it's doable and NOT Challenging so maybe we can implement it later if we have time for it. That's why it's restored but not assigned to any sprint. " If the TAs provides wrong info then this is a problem " !

You can still implement the said feature, but with a decreased degree of realism and without using the camera. For example, if you detect an obstacle you perform evasive maneuvers and try to log how much you strayed away from your path.
Then kind of" blindly" try to get back to where your original track should have been. No need to use the camera.

**Comment by bassamEldesouki** [comment]
Thanks for the clarification, we will see if we are going to implement it in the future :)

**Comment by ChrisAxt** [comment]
We've decided to remove this user story as it does not suit our project anymore.
