### ISSUE TITLE
Passenger access possibilities

### ISSUE THREAD

**Issue by bassamEldesouki** [DIT112-V21/group-07#62]
As a passenger I want to be able to get access to my own user interface so that later I can send requests or view info about the trip.

**Acceptance criteria**
62.1 As a passenger I want to be able to press "I am a passenger" button so I get access to my interface.

**Dependency**
Should not be done before #70

**Comment by bassamEldesouki** [comment]
This user story is edited upon the feedback from the customer (Truong) that passengers shouldn't have to sign in for more friendly application.

**Comment by alrapal** [comment]
Regarding this user story, it is connected to the #66 regarding the selection of the type of user.

Acceptance criteria mention the need of pressing a button to be redirected toward a passenger interface / driver interface for both issues. 
A prototype of this selection page is done for the #66 in the corresponding branch (Driver_Access_Possibilities). 
Therefore, no need to make this page from scratch =)

**Comment by bassamEldesouki** [comment]
The user story doesn't mention anything about making the page from scratch, it could be done after the driver access possibilities :)

**Comment by alrapal** [comment]
> The user story doesn't mention anything about making the page from scratch, it could be done after the driver access possibilities :)

I know, but it does mention being able to click on a button, just like #66. But there is not user selection page in the master, so it needed to be done in order to fulfil the acceptance criteria. I just inform the person that will take this user story that work has partly been done since #66 is related, so we don't do double work 😃 .

**Comment by alrapal** [comment]
(misscliked and closed the issue by accidente haha)

**Comment by alrapal** [comment]
I will add a dependency to #66 to avoid double work then =) 
-> felt clearer to create a user type selection user story. Done with #70
