### ISSUE TITLE
Driver access possibilities 

### ISSUE THREAD

**Issue by bassamEldesouki** [DIT112-V21/group-07#66]
**User story**
As an a driver I want to be able to sign in to the application so that I can drive the bus if I am a driver and at my working hours.
***
**Acceptance criteria**
66.1 As a driver I want to be able to press "I am a driver" button so I log into my interface.
66.2 The bus driver shall get access to their UI only when they enter the right username and password.
66.3 Empty usernames are not accepted.
***
**Dependencies**
#70

**Comment by alrapal** [comment]
Created a new issue with the type of user selection #70 to complete this one since there was no user type selection page in the master.

**Comment by alrapal** [comment]
After a meeting, we felt that the registering part would be assumed to be taken care of through a separated client by the company.
(This is out of the scope of this project, so it will become an assumption, unless we have time to develop it.)
