### ISSUE TITLE
Measure the distance

### ISSUE THREAD

**Issue by ediz-genc** [DIT112-V21/group-07#8]
**User Story**
As an owner, I would like to be able to measure the distance traveled by the car so that I can keep an eye on the total milage.

**Acceptance Criteria** 
8.1 The traveled distance needs to be measured.
8.2 Unit of the measurement is going to be in meter.

**Comment by ediz-genc** [comment]
Measuring the distance has been implemented.

**Comment by bassamEldesouki** [comment]
Done and merged to master!
