### ISSUE TITLE
Passenger bar-code

### ISSUE THREAD

**Issue by ediz-genc** [DIT112-V21/group-07#80]
**User Story**
As a passenger, I want to be able to have a bar-code button to be able to scan the bus bar-code so that I know which bus I am traveling and which route I am on.

**Acceptance Criteria**
80.1 Passenger UI shall have a bar-code button.
80.2 When bar-code scanned, it shall display information of the bus and route.

**Comment by juliavankirk** [comment]
We did not hear from Truong about this requirement, so we have decided to forgo this feature.

**Comment by ediz-genc** [comment]
**Additional information of closure of this issue #80 :** 
#80 This requirement was planned by everyone together with Truong mostly as an assumption in the Sprint 4 review meeting which is held by Truong. Upon our question to Truong by e-mail, we have no response. Due to the date of the final project delivery and no response from Truong, we as Group-7 decided to close this issue without implementing it.
