### ISSUE TITLE
Write the User Manual

### ISSUE THREAD

**Issue by alrapal** [DIT112-V21/group-07#81]
The user manual should contain a description of the features as well as an installation guide. 
**Note:** Update the user manual index as new sections are added :)

- [x] User type selection
- [x] Driver's login page

Driver's dashboard
- [x] Video feed (camera)
- [x] Control panel (limit speed, cruise control, next stop, parking, brake)
- [x] Information panel (speed, stop/assistance, distance)
- [x] Bus line panel (line, stop name, stop list)

Passenger's dashboard
- [x] Request stop
- [x] Request accessibility

Connectivity 
- [x] MQTT
- [x] Connectivity loss

Vehicle automated behaviour
- [x] Obstacle avoidance
- [x] Emergency break
- [x] Slow down smoothly

**Comment by juliavankirk** [comment]
I’m still working on the screenshots and polishing the final draft, hence reopening.

**Comment by juliavankirk** [comment]
Updated the user manual to include guidance on the passenger dashboard. The user manual should now be complete, and this issue is closed henceforth.
