### ISSUE TITLE
Write final report

### ISSUE THREAD

**Issue by alrapal** [DIT112-V21/group-07#82]
### Tasks
***
- Group contributions.
   - _An overall description of how each of the team members contributed to the system and the group-work._
   - _Do not forget to mention work that might not be version controlled as well as each member's GitHub username._
- Post-mortem.
   - _Evaluate and describe your group's work and product._
   - _What would you do differently?_
- A group photo along with your names.

**Comment by iachella** [comment]
Final report has been filled out by all members, and submitted on Canvas (5 Jun at 22:42) by @edizgenc2021 :)
