### ISSUE TITLE
Youtube video

### ISSUE THREAD

**Issue by ediz-genc** [DIT112-V21/group-07#91]
**Tasks**
***
- Demonstrate a Youtube video with a demo of the full functionality and accomplishments of the project.
- A link to demo video in Youtube shall be included in the README.md.
- No length limit.
- Shall showcase the entire functionality of the product.
- Shall explain the problem the system solves and its business potential.
- Includes any other technical or otherwise details that it fits.

**Comment by iachella** [comment]
First draft of the video (accessible only to team members)
https://drive.google.com/file/d/1gCM-OtRzkBp71A5TeYkADm93erVZSbwj/view?usp=sharing
